isApproved cannot be called without level.
strangerstudios/pmpro-approvals pull request #194
Opened 2024-10-25 18:40 UTC by MaximilianoRicoTabo

BUGFIXING: Removed calls to isApproved without a level id.

<img width="1704" alt="image" src="https://github.com/user-attachments/assets/3876e311-abe7-477c-8d59-717da7f5c157">

### All Submissions:

* [x] Have you followed the [Contributing guideline](CONTRIBUTING.MD)?
* [x] Does your code follow the [WordPress' coding standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/)?
* [x] Have you checked to ensure there aren't other open [Pull Requests](../../pulls) for the same update/change?

* [x] Have you added an explanation of what your changes do and why you'd like us to include them?
* [x] Have you successfully run tests with your changes locally?

### Changelog entry

> Enter a summary of all changes on this Pull Request. This will appear in the changelog if accepted.

2024-10-25 19:18 UTC, MaximilianoRicoTabo commented
This gist can be added to the code snippets to fix the bug in the mean time
https://gist.github.com/MaximilianoRicoTabo/a9408b80b6eb31c762ebac459ffadd1a

2025-01-23 11:32 UTC, andrewlimaza commented
@MaximilianoRicoTabo are there cases where this happens? This is intentionally built this way to show a warning when calling isApproved and there's no level.

Does this happen for any of our Add Ons? I can replicate this warning by explicitly calling `PMPro_Approvals::isApproved( null, $user_id );`

2025-01-23 13:17 UTC, andrewlimaza commented
My solution that I'm thinking of would:

* In the `getUserApproval` method, we get a random membership level. We should get all levels and see which ones require approval. It'd be okay to get any level they may have (mmpu) and use that as a reference instead.

* Remove the `_doing_it_wrong_` function call, as we don't pass level ID's when using `[membership] ... some content ... [/membership]` (Blank levels in this case = any level). This warning was added in the past, probably before the membership shortcode access filter and needs to be updated.

2025-01-23 13:18 UTC, andrewlimaza requested changes
Please see alternative solution.

2025-01-23 13:52 UTC, MaximilianoRicoTabo commented
I'll rework this one. thanks @andrewlimaza 



> are there cases where this happens? This is intentionally built this way to show a warning when calling isApproved and there's no level.

Yes, It happened to a client. I pasted the screenshot in the PR description.

2025-01-23 14:06 UTC, andrewlimaza commented
I managed to replicate it using just `[membership] some content [/membership]` which doesn't pass any level ID's to the approval function.

In future it would help to explicitly state the steps to replicate the issue as well as screenshots. I had to dig around code to realize how to replicate it as I couldn't determine from the screenshot supplied.

2025-01-23 21:20 UTC, MaximilianoRicoTabo commented
Removed the  _doing_it_wrong_ an kept all the rest the way it was. I think we can discuss `getUserApproval` signature and expected behavior in the scope of MMPU support. Makes more sense

2025-02-25 20:24 UTC, dparker1005 commented
Should the `pmpro_member_shortcode_access()` function needed anymore? It seems like the `pmpro_has_membership_level()` function should prevent access to the `[membership]` shortcode regardless.

Upon testing, if I comment out the line to hook `pmpro_member_shortcode_access()`, `[membership] some content [/membership]` does not work as expected but `[membership levels="21"] some content [/membership]` does. It turns out that our `pmpro_has_membership_level()` function does not properly handle an empty `$levels` parameter properly (which should check for any level).

With this in mind, the cleanest path forward is likely deprecating the `pmpro_member_shortcode_access()` function (which appears to be the only time that we call `isApproved()` without a level ID allowing us to keep the `doing_it_wrong` warning) and updating the `pmpro_has_membership_level()` method to work properly for empty `$level` calls.

We can then go ahead and deprecate the `pmpro_member_shortcode_access` shortcode in PMPro as this is the only Add On that was using it and filtering `pmpro_has_membership_level` is a more effective solution.

@MaximilianoRicoTabo Let me know if this all makes sense. Hopefully this doesn't conflict with the other open MMPU PR too much

2025-02-27 19:24 UTC, dparker1005 approved these changes

2025-03-03 16:38 UTC, merged